### ISSUE TITLE
bridgeに接続しているVMに疎通できなくなる

### ISSUE THREAD

**Issue by tsuzu** [tsuzu-home/k8s#1]
大体1日経つと接続できなくなる(サンプル数2)ので、cronで動いてる何かが原因では? 感はある
とりあえずそれ止めてみるか、という気持ち

**Comment by tsuzu** [comment]
```
network:
  ethernets:
    eno1:
      dhcp4: false
  bridges:
    br0:
      interfaces:
        - eno1
      dhcp4: true
      critical: yes
  version: 2
```

netplanでcriticalは指定してるのでなんでそんなことになるかはわからん
